name: robotlearning-inference
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - pip:
      - "lerobot[multi_task_dit,feetech]"
      - huggingface_hub
